version: "3"
services:
  server:
    build: docker/node
    image: node:14
    tty: true
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8080:3000"
    working_dir: /usr/src/app
    command: [ bash, -c, "npm install && npm start" ]